### PR TITLE
Corrected image reference

### PR DESCRIPTION
**Pull request by comsystan**
Dear @ctrueden
Many thanks for the merge and for the hint regarding the image linking.

Helmut Ahammer

### CODE REVIEW

**Comment by ctrueden** [comment]
@comsystan Thanks!

I have now added you to the collaborators list, so you should be able to directly make edits without needing to file PRs anymore. Though you are still welcome to file PRs if you would like someone to review your changes before they get merged. It's up to you.

**Comment by comsystan** [comment]
Thank you @ctrueden , for including me in the list of collaborators!  I successfully merged some changes but unfortunately, the ComsystanJ plugin link on the list-of-extensions page does not work and I can not figure out why.

@comsystan

**Comment by ctrueden** [comment]
The page needed the `.md` extension. I added it (a44b2f1cf9014e42ae428dce9b2ff171bf10e89a), and the page is [now live](https://imagej.net/plugins/comsystanj).

**Comment by comsystan** [comment]
Thanks a lot @ctrueden! I completely overlooked that.

**Pull request merged**
