### PR TITLE
Update spim-workflow-manager-for-hpc.md

### PR DESCRIPTION
**Pull request by sebherbert**
@velissarious @xulman 
I believe the update site name has changed? I went ahead and proposed the change, I hope I'm not wrong :)

### CODE REVIEW

**Review by velissarious — APPROVED** [review]
Thank you for the improvement! :)
This is indeed the case.
However, in order to use the functionality described in this page, there must be present and configured a HEAppE Middleware of a compatible version on the remote cluster.
The new features use a direct SSH connection to the remote cluster and focus on parallelization of Fiji macro and Jython scripts.

**Comment by ctrueden** [comment]
@velissarious If you like this PR, then please merge it.

**Comment by ctrueden** [comment]
@sebherbert @velissarious Do we have a consensus on how to proceed? Shall I merge this? Are changes needed? Should I close it?

**Comment by sebherbert** [comment]
They are working on underlying mechanisms at the moment, that will have to be integrated afterwards, but in the meantime this modification is needed.
I believe it can be merged (but I still feel uncomfortable doing it considering I'm not part of the dev team for this plugin).

**Comment by ctrueden** [comment]
Thanks, all!

**Pull request merged**
