### PR TITLE
Add YourKit references and logo to TrackMate acknowledgements.

### PR DESCRIPTION
**Pull request by tinevez**

### CODE REVIEW

**Comment by ctrueden** [comment]
@tinevez Is the wording of this up for debate? Or do you need it to be the way it is for legal reasons?

I'm guessing TrackMate just uses YourKit Java Profiler? If so, and the wording can be changed, I'd propose this more concise blurb instead:

> ```
> TrackMate development uses
[YourKit Java Profiler](https://www.yourkit.com/java/profiler) as a
profiling tool. YourKit supports open source projects with innovative and
intelligent tools for monitoring and profiling Java and .NET applications.
>
> YourKit logo
> ```

What do you think?

**Comment by ctrueden** [comment]
Hmm, it looks like this change was already pushed to the mainline with cab06e2335561049e6a08661b225a972186b75f6, so I'll close this.

**Comment by tinevez** [comment]
This is what Anton at YourKit asked me to put. 
We can ask to change it but YourKit is pretty useful to TrackMate devel.

**Comment by ctrueden** [comment]
@tinevez Fair enough. Merged!

**Comment by ctrueden** [comment]
Ach, I should have rebuilt this branch before merging. On it now.

**Pull request merged**
