### PR TITLE
Add a `More...` menu for software and libraries

### PR DESCRIPTION
**Pull request by oeway**
In the menu, if one only click the arrow button to explore the options, it's not obvious that all the other software or libraries items are listed in the root page, adding a `More...` menu would make it easy to explore the menu entries.

### CODE REVIEW

**Comment by oeway** [comment]
Any objection to this? I will merge later.

**Comment by ctrueden** [comment]
I do not like it aesthetically, bit it is pragmatic. So I am torn.

**Comment by oeway** [comment]
@ctrueden The alternative solutions are 1) list all the libraries/software in the menu 2) make sure we show the root page when we click the arrow icon of `Software` and `Libraries`. Would you prefer that? I don't know how to do that though.

**Comment by ctrueden** [comment]
I think I just need to get over my dislike of having two links in the menu that go to the same page.

I was about to write a suggestion that we could make Software into a non-link, and then the More... entry could exist and link to the /software page with the list, but that's kinda nuts. Why _not_ have the Software node also link there? No reason other than pedantry.

What about Events, though? Would you also put a More... link at the bottom of the Explore : Events menu? Because it has a similar issue, that all past events are enumerated on the main Events page, and not listed otherwise in the menu.

**Comment by oeway** [comment]
> I think I just need to get over my dislike of having two links in the menu that go to the same page.

Well, we can also remove the link from the root element. The menu is like a folder, and the page is the content of a file. It's a bit counter-intuitive that when you click a directory, it opens the files/subfolders, but in the meantime the folder itself is a file, it opens.

> What about Events, though?

I missed that, yes, I would do the same as software and libraries if that contains more items.

**Comment by ctrueden** [comment]
> It's a bit counter-intuitive that when you click a folder, it list the files/subfolders, but in the meantime the folder itself is a file, it opens.

Yeah. But it also bloats the menu to _not_ do it that way. If we make it so all non-leaf elements are not links, we need to then create links for all the content currently linked by those. Upon reflection, rather than adding "More..." leaf items, I'd rather make it so that expanding a menu section always loads that page. It will mean people often load these non-leaf pages even when they are shooting for content deeper down in the menu, but if it annoys people, they can learn to use the search bar. :stuck_out_tongue:

**Comment by ctrueden** [comment]
Sorry again for the delay. I'm going to merge this as is, until (if ever) we come up with something better. Thanks!

**Pull request merged**
