### PR TITLE
Update user-guides.md

### PR DESCRIPTION
**Pull request by cam-nowell**
Update bit.ly links to current version of manual and demo images for Fiji Training notes

### CODE REVIEW

**Comment by ctrueden** [comment]
Can existing `bit.ly` links not be updated to new URLs?

If not, I see no point in using them. One advantage of bit.ly links is brevity, to share via print media and so on. Another is obfuscation, should you need that. But for the wiki, we actively want to avoid obfuscation, and the brevity does not matter. Therefore: could you instead please just use the actual links?

**Comment by cam-nowell** [comment]
That's a good point, unfortunately I've just found that the free version of bit.ly doesn't allow editing the links......

Both resources now have DOIs and i keep that page up to date, so probably best to use the DOI link instead.

Should we cancel this edit and i create another request with the DOI links instead?

**Comment by ctrueden** [comment]
@cam-nowell If you push additional commits to this same branch (`patch-2` on your fork), it will update the PR here without needing to start a new one. Or if you aren't comfortable enough with git for that, then I can just make the changes directly—in that case, just let me know the URLs you would like used.

**Comment by cam-nowell** [comment]
I edited the page but it tells me i don;t have write access so made a new branch anyway.

**Comment by ctrueden** [comment]
> I edited the page but it tells me i don;t have write access so made a new branch anyway.

@cam-nowell Looks like your invite expired. I sent a new one. You should have an email; or else go to https://github.com/imagej/imagej.github.io and look for a banner at the top of the page with the invitation link. Once you accept it, you'll have write access.

**Comment by ctrueden** [comment]
Work completed in af358ebf17ff8c5cb3e4f62dfe5b55db3714b20b. Thanks a lot @cam-nowell for helping to maintain this material! 👍

**Pull request closed without merging**
