### PR TITLE
Update 3D_cyclorama.md

### PR DESCRIPTION
**Pull request by HarryRos**

### CODE REVIEW

**Review by HarryRos — COMMENTED** [review]
I am the author of this page.

How can I edit my own page without added delays?

**Comment by ctrueden** [comment]
@hinerm @frauzufall @elevans I think it makes sense to add @HarryRos and all plugin page maintainers as individual collaborators to this repo so they can make immediate changes. What do you think?

**Comment by elevans** [comment]
Sounds good to me! Can't think of any reasons why not.

**Comment by HarryRos** [comment]
Thanks, guys!

**Comment by hinerm** [comment]
@elevans @ctrueden @elevans we now have an [ij-plugin-maintainers](https://github.com/orgs/imagej/teams/ij-plugin-maintainers/) team where we can add people.

**Comment by ctrueden** [comment]
@hinerm I suggest not to have that team, and instead add everyone as external collaborators directly to this repository. Otherwise:

1. Everyone will have to accept an invitation into the imagej org; and
2. Everyone will have write access to _all_ repositories in this org, as opposed to only the website.

**Comment by hinerm** [comment]
@ctrueden done. Didn't realize it would trigger an org invite. That's annoying.

@HarryRos sorry for the confusion! You should be added to this repo now, in any case.

**Comment by HarryRos** [comment]
Thank you for taking care of this

**Pull request merged**
